// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace CS872_WebApp
{
    public partial class BillingModel
    {
        /// <summary>
        /// model input class for BillingModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"num_rooms")]
            public float Num_rooms { get; set; }

            [ColumnName(@"num_people")]
            public float Num_people { get; set; }

            [ColumnName(@"housearea")]
            public float Housearea { get; set; }

            [ColumnName(@"is_ac")]
            public float Is_ac { get; set; }

            [ColumnName(@"is_tv")]
            public float Is_tv { get; set; }

            [ColumnName(@"is_flat")]
            public float Is_flat { get; set; }

            [ColumnName(@"ave_monthly_income")]
            public float Ave_monthly_income { get; set; }

            [ColumnName(@"num_children")]
            public float Num_children { get; set; }

            [ColumnName(@"is_urban")]
            public float Is_urban { get; set; }

            [ColumnName(@"amount_paid")]
            public float Amount_paid { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for BillingModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("BillingModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
